### ISSUE TITLE
RPC Button 404

### ISSUE THREAD

**Issue by Lukas-Batema** [RuiNtD/SVRichPresence#32]
Dear RuiNtD,
&emsp;&emsp;The RPC button that leads to your (assumingly) old GitHub Account's `*.github.io` (https://faynealdan.github.io/, or in this case, https://faynealdan.github.io/SVRichPresence/) domain leads to a 404, as it is not under your (assumingly once again) new GitHub username. Look at the image below for the issue.

![image](https://github.com/RuiNtD/SVRichPresence/assets/55695493/89ee858f-23c9-4dff-85c5-b5a2dabf5801)

**Comment by RuiNtD** [comment]
Thanks for letting me know. I've updated the link and pushed out a quick update for this.
