### ISSUE TITLE
[Suggestion] Support i18n

### ISSUE THREAD

**Issue by Tenebrosful** [RuiNtD/SVRichPresence#35]
Should be nice to have multi-lang sync with game lang for Activity and GameInfo, can translate in french if need

**Comment by RuiNtD** [comment]
Unfortunately, Activity can't be easily translated because it's actually generated by Stardew Valley itself. There's a debugPresenceString field in Game1 that is constantly updated in various parts of the Stardew code, in English only, but never actually used.

**Comment by RuiNtD** [comment]
Also, if I added i18n, I would also want the upcoming config menu translated. I also don't actually know how to do translation outsourcing.

**Comment by Tenebrosful** [comment]
I think you can look at https://stardewvalleywiki.com/Modding:Modder_Guide/APIs/Translation

**Comment by Tenebrosful** [comment]
> Unfortunately, Activity can't be easily translated because it's actually generated by Stardew Valley itself. There's a debugPresenceString field in Game1 that is constantly updated in various parts of the Stardew code, in English only, but never actually used.

When i was talking about this, i was thinking about strings like https://github.com/RuiNtD/SVRichPresence/blob/114f72c1a2048426dc5facdbe9a0f45cd402a3c6/RichPresenceMod.cs#L79 for exemple that are hardcoded

**Comment by Tenebrosful** [comment]
Actually i learned how to use visual studio sooooooooo i can pull request it yeay

**Comment by RuiNtD** [comment]
GameVerb, GameNoun, and GameInfo are perfectly fine to be translated. As for [where I set GamePresence](https://github.com/RuiNtD/SVRichPresence/blob/114f72c1a2048426dc5facdbe9a0f45cd402a3c6/RichPresenceMod.cs#L79-L82), those are only meant to provide more details, where the game would just provide me with "In menus". Any other activity would be in English. I could probably work around this by translating each possible vanilla message, but that would be a lot of additional effort.

**Comment by RuiNtD** [comment]
Altho, as for GameVerb, GameNoun, and GameInfo, I'm probably going to condense those into one tag.
