### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by RuiNtD** [RuiNtD/SVRichPresence#5]
Stardew Valley has enabled out of the box Linux support! Unfortunately, Mac support is broken due to a problem with the Discord RPC library. See Lachee/discord-rpc-csharp#163

**Comment by FayneAldan** [comment]
Linux support has been fixed. Mac support relies on Lachee/discord-rpc-csharp#163

**Comment by RuiNtD** [comment]
Closing this ticket as I have no personal interest in supporting Mac. PRs are welcome but since I have no idea way to test on Mac, I will continue to say it isn't supported.
